#!/bin/bash

# Check if a file path is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: ./count_tokens <file_path>"
    exit 1
fi

FILE_PATH=$1

# Call the Python script and pass the file path
python3 src/num_tokens.py "$FILE_PATH"
