# Generated by Django 4.2.6 on 2023-12-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_prompts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
